@echo off
echo Compilando documento LaTeX...
pdflatex IPLeiriaMain.tex
echo Generando glosarios...
makeglossaries IPLeiriaMain
echo Procesando bibliografia...
biber IPLeiriaMain
echo Segunda compilacion...
pdflatex IPLeiriaMain.tex
echo Tercera compilacion final...
pdflatex IPLeiriaMain.tex
echo ¡Compilacion completada!
echo El archivo PDF se encuentra en: IPLeiriaMain.pdf
pause
